[server]
host = "localhost"
port = 4000

[jaeger]
agent_endpoint = "http://localhost:4317"

[agent]
common = "StockinfoRuntime"
sec_gov = "webmaster@my-domain.com"

[cors]
origins = ["localhost:4000"]
allow_all_subdomains_of = ["localhost"]

[pg]
host = "localhost"
port = 5432
dbname = "postgres"
user = "postgres"
password = "postgres"
pool = { max_size = 16, timeouts.wait = { secs = 5, nanos = 0 }}

[redis]
url = "redis://localhost:6379"
pool = { max_size = 10, timeouts.wait = { secs = 2, nanos = 0 }}

[keys]
data_go_kr = "key"
dart = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[urls]
kr_price = "https://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService/getStockPriceInfo"
kr_company = "https://apis.data.go.kr/1160100/service/GetKrxListedInfoService/getItemInfo"
kr_krx_price = "http://data.krx.co.kr/comm/bldAttendant/getJsonData.cmd"
kr_krx_price_referer = "http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201020101"
kr_krx_price_date = "http://data.krx.co.kr/comm/bldAttendant/executeForResourceBundle.cmd"
us_ticker = "https://www.sec.gov/files/company_tickers.json"
us_submissions = "https://data.sec.gov/submissions/CIK"
us_price = "https://query1.finance.yahoo.com/v8/finance/chart"
dart_statement = "https://opendart.fss.or.kr/api/fnlttSinglAcntAll.json"
dart_index = "https://opendart.fss.or.kr/api/fnlttSinglIndx.json"
dart_code = "https://opendart.fss.or.kr/api/corpCode.xml"
edgar = "https://www.sec.gov/Archives/edgar/data"
